Universe   = vanilla
Executable = /d/grid17/septian/Eta3PiDalitz/batch_run/PhotonBeamEnergySystematic/run.sh
Arguments  = 0 data_2017 0 t01506_ExpPolyBkg PhotonBeamEnergy $(Process) 32

Log        = /d/grid17/septian/Eta3PiDalitz/batch_run/PhotonBeamEnergySystematic/log_data_2017_t01506_ExpPolyBkg_PhotonBeamEnergy/log_$(Process).log
Output     = /d/grid17/septian/Eta3PiDalitz/batch_run/PhotonBeamEnergySystematic/log_data_2017_t01506_ExpPolyBkg_PhotonBeamEnergy/out_$(Process).log
Error      = /d/grid17/septian/Eta3PiDalitz/batch_run/PhotonBeamEnergySystematic/log_data_2017_t01506_ExpPolyBkg_PhotonBeamEnergy/err_$(Process).log

transfer_input_files = /d/grid17/septian/Eta3PiDalitz/batch_run/PhotonBeamEnergySystematic/run.sh,/d/grid17/septian/Eta3PiDalitz/macros/runEta3PiSelectorParallelNew.sh

queue Process from seq 0 7 |