Universe   = vanilla
Executable = /d/home/septian/Eta3PiDalitz/batch_run/bootstrap/run.sh
Arguments  = 10092022 $(Process)

Log        = /d/home/septian/Eta3PiDalitz/batch_run/bootstrap/log/log_$(Process).log
Output     = /d/home/septian/Eta3PiDalitz/batch_run/bootstrap/log/out_$(Process).log
Error      = /d/home/septian/Eta3PiDalitz/batch_run/bootstrap/log/err_$(Process).log

transfer_input_files = /d/home/septian/Eta3PiDalitz/batch_run/bootstrap/run.sh,/d/home/septian/Eta3PiDalitz/batch_run/bootstrap/run_fit.sh
transfer_output_files = out_$(Process) 

queue Process from seq 0 999 |
